### ISSUE TITLE
refactoring from jQuery to modern JavaScript

### ISSUE THREAD

**Issue by bjohansebas** [expressjs/expressjs.com#1590]
As discussed in #1568, these will be the next steps to stop using jQuery in favor of the browser's API:

- [x] **First PR (Refactor Menu):** #1568
  - Remove dropit
  - Remove functions related to dropit
  - Refactor the menu according to the new structure
  - Create styles according to the new structure
  - Add new menu functionality in a new file

- [x] **Second PR (Remove Unused Functions):** #1698
  - Remove ismobil.js
  - Remove logic for page editing (no longer used since the footer was updated)
  - Remove logic for [`window.location.pathname === '/3x/api.html'`](https://github.com/expressjs/expressjs.com/blob/83cf6069eca7670210c856fca51d6db4dded2c0d/js/app.js#L121) (no longer used since almost all URLs now go to `/en/*`)
  - Remove function related to [`#tags-side-menu`](https://github.com/expressjs/expressjs.com/blob/83cf6069eca7670210c856fca51d6db4dded2c0d/js/app.js#L155)

- [ ] **Third PR (Adapt get elements):**
  - Update scroll top logic
  - Adapt element retrieval and events
  - Add overlay logic to the menu
  - Adapt code highlighting

- [ ] **Fourth PR (Adapt Functions):**
  - Update logic for the i18n banner
  - Update logic for the closer title (used in the API)
  - Adapt cookies logic to ES6

- [ ] **Fifth PR (Remove jQuery Dependency, #1569):**
  - Remove link to jQuery

**Comment by bjohansebas** [comment]
The search bar in dark mode is broken in terms of design. @chrisdel101 Should I fix it in the first PR or better in a separate PR?

![image](https://github.com/user-attachments/assets/5b93173b-37c4-45e7-bbac-b62bac744cbe)

**Comment by chrisdel101** [comment]
I'm just looking at #1590 since I think you fixed it over there right? Sorry
 for delay.

**Comment by bjohansebas** [comment]
@chrisdel101 don't worry, that issue is not fixed yet.

**Comment by chrisdel101** [comment]
Oh is this a different issue? I see. Maybe a small separeate PR would work, but things are getting kind of backed up. Still, it's not really related to the refactor, so separate issue would be my vote.

**Comment by ShubhamOulkar** [comment]
@bjohansebas If you allow me, I like to work on this.

**Comment by bjohansebas** [comment]
@ShubhamOulkar Yes, please finish it.

**Comment by ShubhamOulkar** [comment]
> [@ShubhamOulkar](https://github.com/ShubhamOulkar) Yes, please finish it.

Great, I plan to do it this Sunday.
